export const GET_GROUPS = 'hub/GET_GROUPS';
export const GET_GROUP_MESSAGES = 'hub/GET_GROUP_MESSAGES';
export const NEW_MESSAGE_IN_GROUP = 'hub/NEW_MESSAGE_IN_GROUP';
export const SEND_GROUP_MESSAGE_READ_RECEIPT = 'hub/SEND_GROUP_MESSAGE_READ_RECEIPT';

export const GET_USERS = 'hub/GET_USERS';
export const GET_USER_MESSAGES = 'hub/GET_USER_MESSAGES';
export const NEW_MESSAGE_IN_USER = 'hub/NEW_MESSAGE_IN_USER';
export const SEND_USER_MESSAGE_READ_RECEIPT = 'hub/SEND_USER_MESSAGE_READ_RECEIPT';
